config/routes.rb
Expenses::Application.routes.draw do

#C

  get '/expenses/new' => 'Expenses#new', :as => 'new_expense'
  post '/expenses' => 'Expenses#create', :as => 'expenses'

#R

  get '/expenses' => 'Expenses#index', :as => 'expenses'
  get '/expenses/:id' => 'Expenses#show', :as => 'expense'

#U

  get 'expenses/:id/edit' => 'Expenses#edit', :as => 'edit_expense'
  put 'expenses/:id' => 'Expenses#update', :as => 'expense_url'

#D

  delete 'expenses/:id' => 'Expenses#destroy', :as => 'expense'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :expense_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @expenses = Expense.all
  end

  def new
    @expense=Expense.new
  end

  def create
    @expense = Expense.new(params[:expense])
    if @expense.save
      redirect_to expenses_url
    else
      render 'new'
    end
  end

  def show

    @expense = Expense.find(params[:id])
  end

  def destroy

    @expense = Expense.find(params[:id])
    @expense.destroy
    redirect_to expenses_url

  end

  def edit

   @expense = Expense.find(params[:id])


  end

  def update
  @expense = Expense.find(params[:id])
  @expense.update_attributes(params[:expense])
  redirect_to expenses_url

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/edit.html.erb
<h1> Edit this Expense</h1>

<%= form_for @expense do |e| %>
  <%= e.label :amount, "Amount:" %>
  <%= e.text_field :amount %>
    <p></p>

  <%= e.label :expense_type, "Expense Type:" %>
  <%= e.text_field :expense_type %>
<p></p>
<%= e.submit %>

<% end %>

<%= link_to "Go back to index", expenses_url %>

app/views/expenses/index.html.erb
<h1>Here are the Expenses</h1>

<% @expenses.each do |e| %>
<%= e.expense_type %>
$<%= e.amount %>
<%= link_to "edit this entry", edit_expense_url(e.id) %>
<%= link_to "delete this entry", expense_url(e.id), :method => 'delete' %>
<p></p>
<% end %>

<%= link_to "Create a new Expense", new_expense_url %>

app/views/expenses/new.html.erb
<h1>Add a new Expense</h1>

<%= form_for @expense do |e| %>
  <%= e.label :amount, "Amount:" %>
  <%= e.text_field :amount %>
    <p></p>

  <%= e.label :expense_type, "Expense Type:" %>
  <%= e.text_field :expense_type %>
<p></p>
<%= e.submit %>

<% end %>

<%= link_to "Go back to index", expenses_url %>

app/views/expenses/show.html.erb
<h1>This is the Single Expense</h1>



Expense Type: <%= @expense.expense_type %>

<p></p>

Expense Amount: $<%= @expense.amount  %>
<p></p>
<%= link_to "Link to Index", expenses_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expenses</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>